# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  dependencies:
    environment:
      JVM_OPTS: -Xmx3200m
    docker:
      - image: gaberger/jdk9-graalvm
    steps:
      - checkout
      - run:
          name: Grab deps
          command: clojure -Spath
      - run:
          name: Test V2
          command: clojure -A:testv2
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}
  build_release:
    docker:
      - image: gaberger/jdk9-graalvm
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
            - ~/graalvm-ce-1.0.0-rc2
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
      - run:
          name: Update PATH for GRAALVM
          command: |
            echo 'export PATH=~/project/graalvm-ce-1.0.0-rc2/bin:$PATH' >> $BASH_ENV
            echo 'export JAVA_HOME=~/project/graalvm-ce-1.0.0-rc2' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build Native Image
          command: |
             clojure -A:native-image --graalvm-home ~/runtime/graalvm-ce-1.0.0/graalvm-ce-1.0.0-rc2  
      - run:
          name: Build Uberjar
          command: |
             clojure -A:uberjar

workflows:
  version: 2
  build_and_test:
    jobs:
      - dependencies
      - build_release:
          requires:
            - dependencies

