# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-1.9.0.375
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          working_directory: ~
          command: |
            echo Download GRAALVM
            wget https://github.com/oracle/graal/releases/download/vm-1.0.0-rc2/graalvm-ce-1.0.0-rc2-linux-amd64.tar.gz .
            tar xf graalvm-ce-1.0.0-rc2-linux-amd64.tar.gz
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "deps.edn" }}
          - v1.0.0.-rc2-graalvm
      - run: clj -Spath
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}
      - save_cache:
          paths:
            - ~/graalvm-ce-1.0.0-rc2
          key: v1.0.0-rc2-graalvm
      - run: clj -A:testv2, clj -A:uberjar, clj -A:native-image --graalvm-home ~/graalvm-ce-1.0.0-rc2