# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  prepare:
    docker:
      - image: circleci/clojure:tools-deps-1.9.0.375
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
  dependencies:
    working_directory: ~/dependencies
    docker:
      - image: circleci/clojure:tools-deps-1.9.0.375
    steps:
      - run:
          name: Download GRAALVM
          command: |
            echo Download GRAALVM
            wget https://github.com/oracle/graal/releases/download/vm-1.0.0-rc2/graalvm-ce-1.0.0-rc2-linux-amd64.tar.gz .
      - run:
          name: Prepare GRAALVM
          working_directory: ~
          command: |
            echo Prepare GRAALVM
            tar xf graalvm-ce-1.0.0-rc2-linux-amd64.tar.gz
      - run:
          clj -Spath
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            - v1.0.0.-rc2-graalvm
      - save_cache:
          paths:
            - ~/.m2
            - ~/dependencies
          key: v1-dependencies-{{ checksum "deps.edn" }}

  test:
    docker:
      - image: circleci/clojure:tools-deps-1.9.0.375
    working_directory: ~/repo
    steps:
      - run: clj -A:testv2

workflows:
  version: 2
  build_and_test:
    jobs:
      - prepare
      - dependencies
      - test
